server:
  port: 9090

spring:
  activemq:
    broker-url: tcp://192.168.1.138:61616
    user: admin
    password: admin
#    in-memory: true
#    # \u662F\u5426\u542F\u7528\u8FDE\u63A5\u6C60
#    pool:
#      enabled: true
#      max-connections: 50
  jms:
    pub-sub-domain: false

  data:
    mongodb:
      uri: mongodb://192.168.1.115:27017/tbox_db
      username: tbox
      password: 123456

# \u81EA\u5B9A\u4E49
mymq: springboot-active-queue
