server:
    port: 8060

spring:
    thymeleaf:
        mode: LEGACYHTML5
        cache: false

#自定义
# 不要的时候请全部注释，否则空 异常
#xiaowu:
#    security:
#        browser:
#            loginPage: /demo-signIn.html