
server:
  port: 9090

mybatis:
  mapperLocations: classpath:com/xiaowu/backspringboot/mapping/*.xml
#  typeAliasesPackage: com.xiaowu.backspringboot.dao

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/xiaowu?useSSL=false
        username: root
        password: 123456
        driver-class-name: com.mysql.jdbc.Driver
    thymeleaf:
        mode: LEGACYHTML5
        cache: false