mybatis:
    mapperLocations: classpath:mapper/*.xml
    typeAliasesPackage: com.xiaowu.aysnlog.dao

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/test?useSSL=false
        username: root
        password: 123456
        driver-class-name: com.mysql.jdbc.Driver

    rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest
        listener:
          simple:
            concurrency: 10
            max-concurrency: 20
            prefetch: 5

    mail:
      host: smtp.qq.com
      username: 1981293730@qq.com
      password: ahnvcbsawujrdcga
      properties.mail.smtp.auth: true
      properties.mail.smtp.starttls.enable: true
      properties.mail.smtp.starttls.required: true
      default-encoding: UTF-8
      port: 465
      properties.mail.smtp.socketFactory.port: 465
      properties.mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
      properties.mail.smtp.socketFactory.fallback: false

# 自定义配置
mq:
  queue:
    durable:
    exclusive: ture
    autoDelete: ture
  exchange:
    durable:
    autoDelete: ture

mail.username: 1981293730@qq.com
